### ISSUE TITLE
Python Example?

### ISSUE THREAD

**Issue by dR3b** [Shopify/shadowenv#98]
Hi, 
Is there an example of a Python environment somewhere? Or an example of the command: "source"?
Thanks!

**Comment by dR3b** [comment]
Sorry, I should have described that a little more precisely. With "source" I meant a command like: `source ~/tmp/00-env/wiki/bin/activate`. This command activates a virtual-env for Python. 

The possibility to start a shell command would be great!

**Comment by lugray** [comment]
Shadowenv makes a very intentional decision _not_ to allow sourcing arbitrary code, making the decision to avoid being turing-complete, and providing only a limited means to modify environment variables _quickly_ as you change directories. If `source ~/tmp/00-env/wiki/bin/activate` does nothing but modify environment variables, then it's possible that it could be translated into shadowlisp so that shadowenv can perform this automatically. If not, then you may find that your needs are met by shellhooks, which _can_ do more arbitrary work. Shadowenv makes use of https://github.com/Shopify/hookbook to make registering shellhooks easier, and you may wish to do the same.

**Comment by dR3b** [comment]
Thank you for your reply.

**Comment by lugray** [comment]
This seems resolved. Feel free to re-open if I've misunderstood.
